name: InventoryCap
version: '${project.version}'
main: dev.siea.inventorycap.InventoryCap
api-version: '1.20'
authors: [siea]
commands:
  inventorycap:
    usage: §c/inventorycap help
    aliases: [invc, invcap, ic]
    permission: "inventorycap.admin"
